/* Copyright Statement:
 *
 * This software/firmware and related documentation ("MediaTek Software") are
 * protected under relevant copyright laws. The information contained herein
 * is confidential and proprietary to MediaTek Inc. and/or its licensors.
 * Without the prior written permission of MediaTek inc. and/or its licensors,
 * any reproduction, modification, use or disclosure of MediaTek Software,
 * and information contained herein, in whole or in part, shall be strictly prohibited.
 */
/* MediaTek Inc. (C) 2010. All rights reserved.
 *
 * BY OPENING THIS FILE, RECEIVER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
 * THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
 * RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO RECEIVER ON
 * AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
 * NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
 * SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
 * SUPPLIED WITH THE MEDIATEK SOFTWARE, AND RECEIVER AGREES TO LOOK ONLY TO SUCH
 * THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. RECEIVER EXPRESSLY ACKNOWLEDGES
 * THAT IT IS RECEIVER'S SOLE RESPONSIBILITY TO OBTAIN FROM ANY THIRD PARTY ALL PROPER LICENSES
 * CONTAINED IN MEDIATEK SOFTWARE. MEDIATEK SHALL ALSO NOT BE RESPONSIBLE FOR ANY MEDIATEK
 * SOFTWARE RELEASES MADE TO RECEIVER'S SPECIFICATION OR TO CONFORM TO A PARTICULAR
 * STANDARD OR OPEN FORUM. RECEIVER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND
 * CUMULATIVE LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
 * AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
 * OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY RECEIVER TO
 * MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE.
 */

/*
 * DaVinci pin multiplexing defines
 *
 * Author: Vladimir Barinov, MontaVista Software, Inc. <source@mvista.com>
 *
 * 2007 (c) MontaVista Software, Inc. This file is licensed under
 * the terms of the GNU General Public License version 2. This program
 * is licensed "as is" without any warranty of any kind, whether express
 * or implied.
 */
#ifndef __ASM_ARCH_MUX_H
#define __ASM_ARCH_MUX_H

#define DAVINCI_MUX_AEAW0	0
#define DAVINCI_MUX_AEAW1	1
#define DAVINCI_MUX_AEAW2	2
#define DAVINCI_MUX_AEAW3	3
#define DAVINCI_MUX_AEAW4	4
#define DAVINCI_MUX_AECS4	10
#define DAVINCI_MUX_AECS5	11
#define DAVINCI_MUX_VLYNQWD0	12
#define DAVINCI_MUX_VLYNQWD1	13
#define DAVINCI_MUX_VLSCREN	14
#define DAVINCI_MUX_VLYNQEN	15
#define DAVINCI_MUX_HDIREN	16
#define DAVINCI_MUX_ATAEN	17
#define DAVINCI_MUX_RGB666	22
#define DAVINCI_MUX_RGB888	23
#define DAVINCI_MUX_LOEEN	24
#define DAVINCI_MUX_LFLDEN	25
#define DAVINCI_MUX_CWEN	26
#define DAVINCI_MUX_CFLDEN	27
#define DAVINCI_MUX_HPIEN	29
#define DAVINCI_MUX_1394EN	30
#define DAVINCI_MUX_EMACEN	31

#define DAVINCI_MUX_LEVEL2	32
#define DAVINCI_MUX_UART0	(DAVINCI_MUX_LEVEL2 + 0)
#define DAVINCI_MUX_UART1	(DAVINCI_MUX_LEVEL2 + 1)
#define DAVINCI_MUX_UART2	(DAVINCI_MUX_LEVEL2 + 2)
#define DAVINCI_MUX_U2FLO	(DAVINCI_MUX_LEVEL2 + 3)
#define DAVINCI_MUX_PWM0	(DAVINCI_MUX_LEVEL2 + 4)
#define DAVINCI_MUX_PWM1	(DAVINCI_MUX_LEVEL2 + 5)
#define DAVINCI_MUX_PWM2	(DAVINCI_MUX_LEVEL2 + 6)
#define DAVINCI_MUX_I2C		(DAVINCI_MUX_LEVEL2 + 7)
#define DAVINCI_MUX_SPI		(DAVINCI_MUX_LEVEL2 + 8)
#define DAVINCI_MUX_MSTK	(DAVINCI_MUX_LEVEL2 + 9)
#define DAVINCI_MUX_ASP		(DAVINCI_MUX_LEVEL2 + 10)
#define DAVINCI_MUX_CLK0	(DAVINCI_MUX_LEVEL2 + 16)
#define DAVINCI_MUX_CLK1	(DAVINCI_MUX_LEVEL2 + 17)
#define DAVINCI_MUX_TIMIN	(DAVINCI_MUX_LEVEL2 + 18)

extern void davinci_mux_peripheral(unsigned int mux, unsigned int enable);

#endif /* __ASM_ARCH_MUX_H */
