/* Copyright Statement:
 *
 * This software/firmware and related documentation ("MediaTek Software") are
 * protected under relevant copyright laws. The information contained herein
 * is confidential and proprietary to MediaTek Inc. and/or its licensors.
 * Without the prior written permission of MediaTek inc. and/or its licensors,
 * any reproduction, modification, use or disclosure of MediaTek Software,
 * and information contained herein, in whole or in part, shall be strictly prohibited.
 */
/* MediaTek Inc. (C) 2010. All rights reserved.
 *
 * BY OPENING THIS FILE, RECEIVER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
 * THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
 * RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO RECEIVER ON
 * AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
 * NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
 * SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
 * SUPPLIED WITH THE MEDIATEK SOFTWARE, AND RECEIVER AGREES TO LOOK ONLY TO SUCH
 * THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. RECEIVER EXPRESSLY ACKNOWLEDGES
 * THAT IT IS RECEIVER'S SOLE RESPONSIBILITY TO OBTAIN FROM ANY THIRD PARTY ALL PROPER LICENSES
 * CONTAINED IN MEDIATEK SOFTWARE. MEDIATEK SHALL ALSO NOT BE RESPONSIBLE FOR ANY MEDIATEK
 * SOFTWARE RELEASES MADE TO RECEIVER'S SPECIFICATION OR TO CONFORM TO A PARTICULAR
 * STANDARD OR OPEN FORUM. RECEIVER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND
 * CUMULATIVE LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
 * AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
 * OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY RECEIVER TO
 * MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE.
 */

/* This file is automatically generated.  Do not edit. */
/*
 * Security object class definitions
 */
    S_(NULL)
    S_("security")
    S_("process")
    S_("system")
    S_("capability")
    S_("filesystem")
    S_("file")
    S_("dir")
    S_("fd")
    S_("lnk_file")
    S_("chr_file")
    S_("blk_file")
    S_("sock_file")
    S_("fifo_file")
    S_("socket")
    S_("tcp_socket")
    S_("udp_socket")
    S_("rawip_socket")
    S_("node")
    S_("netif")
    S_("netlink_socket")
    S_("packet_socket")
    S_("key_socket")
    S_("unix_stream_socket")
    S_("unix_dgram_socket")
    S_("sem")
    S_("msg")
    S_("msgq")
    S_("shm")
    S_("ipc")
    S_(NULL)
    S_(NULL)
    S_(NULL)
    S_(NULL)
    S_(NULL)
    S_(NULL)
    S_(NULL)
    S_(NULL)
    S_(NULL)
    S_(NULL)
    S_(NULL)
    S_(NULL)
    S_(NULL)
    S_("netlink_route_socket")
    S_("netlink_firewall_socket")
    S_("netlink_tcpdiag_socket")
    S_("netlink_nflog_socket")
    S_("netlink_xfrm_socket")
    S_("netlink_selinux_socket")
    S_("netlink_audit_socket")
    S_("netlink_ip6fw_socket")
    S_("netlink_dnrt_socket")
    S_(NULL)
    S_(NULL)
    S_("association")
    S_("netlink_kobject_uevent_socket")
    S_("appletalk_socket")
    S_("packet")
    S_("key")
    S_(NULL)
    S_("dccp_socket")
    S_("memprotect")
    S_(NULL)
    S_(NULL)
    S_(NULL)
    S_(NULL)
    S_(NULL)
    S_(NULL)
    S_("peer")
    S_("capability2")
    S_(NULL)
    S_(NULL)
    S_(NULL)
    S_(NULL)
    S_("kernel_service")
