/* Copyright Statement:
 *
 * This software/firmware and related documentation ("MediaTek Software") are
 * protected under relevant copyright laws. The information contained herein
 * is confidential and proprietary to MediaTek Inc. and/or its licensors.
 * Without the prior written permission of MediaTek inc. and/or its licensors,
 * any reproduction, modification, use or disclosure of MediaTek Software,
 * and information contained herein, in whole or in part, shall be strictly prohibited.
 */
/* MediaTek Inc. (C) 2010. All rights reserved.
 *
 * BY OPENING THIS FILE, RECEIVER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
 * THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
 * RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO RECEIVER ON
 * AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
 * NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
 * SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
 * SUPPLIED WITH THE MEDIATEK SOFTWARE, AND RECEIVER AGREES TO LOOK ONLY TO SUCH
 * THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. RECEIVER EXPRESSLY ACKNOWLEDGES
 * THAT IT IS RECEIVER'S SOLE RESPONSIBILITY TO OBTAIN FROM ANY THIRD PARTY ALL PROPER LICENSES
 * CONTAINED IN MEDIATEK SOFTWARE. MEDIATEK SHALL ALSO NOT BE RESPONSIBLE FOR ANY MEDIATEK
 * SOFTWARE RELEASES MADE TO RECEIVER'S SPECIFICATION OR TO CONFORM TO A PARTICULAR
 * STANDARD OR OPEN FORUM. RECEIVER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND
 * CUMULATIVE LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
 * AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
 * OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY RECEIVER TO
 * MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE.
 */

/* This file is automatically generated.  Do not edit. */
TB_(common_file_perm_to_string)
    S_("ioctl")
    S_("read")
    S_("write")
    S_("create")
    S_("getattr")
    S_("setattr")
    S_("lock")
    S_("relabelfrom")
    S_("relabelto")
    S_("append")
    S_("unlink")
    S_("link")
    S_("rename")
    S_("execute")
    S_("swapon")
    S_("quotaon")
    S_("mounton")
TE_(common_file_perm_to_string)

TB_(common_socket_perm_to_string)
    S_("ioctl")
    S_("read")
    S_("write")
    S_("create")
    S_("getattr")
    S_("setattr")
    S_("lock")
    S_("relabelfrom")
    S_("relabelto")
    S_("append")
    S_("bind")
    S_("connect")
    S_("listen")
    S_("accept")
    S_("getopt")
    S_("setopt")
    S_("shutdown")
    S_("recvfrom")
    S_("sendto")
    S_("recv_msg")
    S_("send_msg")
    S_("name_bind")
TE_(common_socket_perm_to_string)

TB_(common_ipc_perm_to_string)
    S_("create")
    S_("destroy")
    S_("getattr")
    S_("setattr")
    S_("read")
    S_("write")
    S_("associate")
    S_("unix_read")
    S_("unix_write")
TE_(common_ipc_perm_to_string)

