/* Copyright Statement:
 *
 * This software/firmware and related documentation ("MediaTek Software") are
 * protected under relevant copyright laws. The information contained herein
 * is confidential and proprietary to MediaTek Inc. and/or its licensors.
 * Without the prior written permission of MediaTek inc. and/or its licensors,
 * any reproduction, modification, use or disclosure of MediaTek Software,
 * and information contained herein, in whole or in part, shall be strictly prohibited.
 */
/* MediaTek Inc. (C) 2010. All rights reserved.
 *
 * BY OPENING THIS FILE, RECEIVER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
 * THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
 * RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO RECEIVER ON
 * AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
 * NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
 * SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
 * SUPPLIED WITH THE MEDIATEK SOFTWARE, AND RECEIVER AGREES TO LOOK ONLY TO SUCH
 * THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. RECEIVER EXPRESSLY ACKNOWLEDGES
 * THAT IT IS RECEIVER'S SOLE RESPONSIBILITY TO OBTAIN FROM ANY THIRD PARTY ALL PROPER LICENSES
 * CONTAINED IN MEDIATEK SOFTWARE. MEDIATEK SHALL ALSO NOT BE RESPONSIBLE FOR ANY MEDIATEK
 * SOFTWARE RELEASES MADE TO RECEIVER'S SPECIFICATION OR TO CONFORM TO A PARTICULAR
 * STANDARD OR OPEN FORUM. RECEIVER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND
 * CUMULATIVE LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
 * AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
 * OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY RECEIVER TO
 * MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE.
 *
 * The following software/firmware and/or related documentation ("MediaTek Software")
 * have been modified by MediaTek Inc. All revisions are subject to any receiver's
 * applicable license agreements with MediaTek Inc.
 */

#ifndef __MT6516_MM_MEM_H__
#define __MT6516_MM_MEM_H__

#define INTERNAL_SRAM_DEVNAME "MT6516_Int_SRAM"

typedef enum 
{
    INTERNAL_SRAM_PNG_DECODER = 1,    
    INTERNAL_SRAM_JPEG_DECODER = 2,
    INTERNAL_SRAM_H264_DECODER_MC_LINE_BUF = 3,
    INTERNAL_SRAM_H264_DECODER_MC_MV_BUFFER = 4,
    INTERNAL_SRAM_H264_DECODER_DEC_DEB_BUF = 5,
    INTERNAL_SRAM_H264_DECODER_DEC_DEB_DAT_BUF0 = 6,
    INTERNAL_SRAM_H264_DECODER_DEC_DEB_DAT_BUF1 = 7,
    INTERNAL_SRAM_H264_DECODER_CALVC = 8,
    INTERNAL_SRAM_MPEG4_DECODER_DATA_STORE = 9,
    INTERNAL_SRAM_MPEG4_DECODER_DACP = 10,
    INTERNAL_SRAM_MPEG4_DECODER_MVP = 11,
    INTERNAL_SRAM_MPEG4_DECODER_QS = 12,
    INTERNAL_SRAM_MPEG4_ENCODER = 13,
    INTERNAL_SRAM_IDP_IRT0 = 14,
    INTERNAL_SRAM_IDP_IRT1 = 15,
    INTERNAL_SRAM_IDP_IRT3 = 16,
    INTERNAL_SRAM_IDP_VDO_ENC_WDMA = 17,
    INTERNAL_SRAM_IDP_JPEG_DMA = 18,
    INTERNAL_SRAM_IDP_PRZ = 19,
    INTERNAL_SRAM_IDP_MP4DEBLK = 20, 
    INTERNAL_SRAM_IDP_PRZ_MCU = 21,
    INTERNAL_SRAM_MAX_USING_INTERNAL_SRAM_DRIVER = 0xFFFFFFFF
} USING_INTERNAL_SRAM_DRIVER;

unsigned int alloc_internal_sram(USING_INTERNAL_SRAM_DRIVER driver_module, UINT32 size, UINT32 byte_alignment);
void free_internal_sram(USING_INTERNAL_SRAM_DRIVER driver_module, UINT32 phy_addr);

#endif //__MT6516_MM_MEM_H__
