/* Copyright Statement:
 *
 * This software/firmware and related documentation ("MediaTek Software") are
 * protected under relevant copyright laws. The information contained herein
 * is confidential and proprietary to MediaTek Inc. and/or its licensors.
 * Without the prior written permission of MediaTek inc. and/or its licensors,
 * any reproduction, modification, use or disclosure of MediaTek Software,
 * and information contained herein, in whole or in part, shall be strictly prohibited.
 */
/* MediaTek Inc. (C) 2010. All rights reserved.
 *
 * BY OPENING THIS FILE, RECEIVER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
 * THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
 * RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO RECEIVER ON
 * AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
 * NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
 * SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
 * SUPPLIED WITH THE MEDIATEK SOFTWARE, AND RECEIVER AGREES TO LOOK ONLY TO SUCH
 * THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. RECEIVER EXPRESSLY ACKNOWLEDGES
 * THAT IT IS RECEIVER'S SOLE RESPONSIBILITY TO OBTAIN FROM ANY THIRD PARTY ALL PROPER LICENSES
 * CONTAINED IN MEDIATEK SOFTWARE. MEDIATEK SHALL ALSO NOT BE RESPONSIBLE FOR ANY MEDIATEK
 * SOFTWARE RELEASES MADE TO RECEIVER'S SPECIFICATION OR TO CONFORM TO A PARTICULAR
 * STANDARD OR OPEN FORUM. RECEIVER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND
 * CUMULATIVE LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
 * AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
 * OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY RECEIVER TO
 * MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE.
 *
 * The following software/firmware and/or related documentation ("MediaTek Software")
 * have been modified by MediaTek Inc. All revisions are subject to any receiver's
 * applicable license agreements with MediaTek Inc.
 */

/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of MediaTek Inc. (C) 2008
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
*  RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE MEDIATEK SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. MEDIATEK SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE.
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*****************************************************************************/

#ifndef _MTK_GPT_SW_H
#define _MTK_GPT_SW_H

#include <mach/mt3351_typedefs.h>

//The operation mode of GPT n
typedef enum
{
    GPT_ONE_SHOT = 0x0000,
    GPT_REPEAT   = 0x0010,
    GPT_KEEP_GO  = 0x0020,
    GPT_FREE_RUN = 0x0030
} GPT_CON_MODE;

//GPT n input clock frequency.
typedef enum
{
    GPT_CLK_DIV_1   = 0x0000,
    GPT_CLK_DIV_2   = 0x0001,
    GPT_CLK_DIV_4   = 0x0002,
    GPT_CLK_DIV_8   = 0x0003,
    GPT_CLK_DIV_16  = 0x0004,
    GPT_CLK_DIV_32  = 0x0005,
    GPT_CLK_DIV_64  = 0x0006,
    GPT_CLK_DIV_128 = 0x0007
} GPT_CLK_DIV;

//The clock source of GPT n
typedef enum
{
    GPT_CLK_NONE = 0,     // turn off the gpt clcok
    GPT_CLK_SYS_CRYSTAL,  // system clock : 13M or 26M Hz
    GPT_CLK_APB_BUS,      // apb bus
    GPT_CLK_RTC           // 32768Hz
} GPT_CLK_SOURCE;

typedef enum
{
    GPT0 = 0,
    GPT1,
    GPT2,
    GPT3,
    GPT4,
    GPT5,
    GPT_TOTAL_COUNT
}GPT_NUM;

typedef struct 
{
    void (*gpt0_func)(UINT16);
    void (*gpt1_func)(UINT16); 
    void (*gpt2_func)(UINT16); 
    void (*gpt3_func)(UINT16);
    void (*gpt4_func)(UINT16); 
    void (*gpt5_func)(UINT16);    
}GPT_Func;

typedef struct
{
    GPT_NUM num;          //GPT1~5
    GPT_CON_MODE mode;    //
    GPT_CLK_SOURCE clkSrc;
    GPT_CLK_DIV clkDiv;
    BOOL bIrqEnable;
    UINT32 u4CompareL;
    UINT32 u4CompareH;
} GPT_CONFIG;


BOOL GPT_Config(GPT_CONFIG config);
void GPT_EnableIRQ(GPT_NUM);
void GPT_DisableIRQ(GPT_NUM);
GPT_NUM GPT_Get_IRQSTA(void);
BOOL GPT_Check_IRQSTA(GPT_NUM numGPT);
void GPT_Init(GPT_NUM timerNum, void (*GPT_Callback)(UINT16));
void GPT_Reset(GPT_NUM numGPT);
void GPT_LISR(void);
void GPT_AckIRQ(GPT_NUM);
void GPT_Start(GPT_NUM);
void GPT_Stop(GPT_NUM);
void GPT_ClearCount(GPT_NUM);
void GPT_SetOpMode(GPT_NUM, GPT_CON_MODE); // set operation mode
GPT_CON_MODE GPT_GetOpMode(GPT_NUM);
void GPT_SetClkDivisor(GPT_NUM, GPT_CLK_DIV);
GPT_CLK_DIV GPT_GetClkDivisor(GPT_NUM);
void GPT_SetClkSource(GPT_NUM, GPT_CLK_SOURCE);
GPT_CLK_SOURCE GPT_GetClkSource(GPT_NUM);
UINT32 GPT_GetCounterL32(GPT_NUM);
UINT32 GPT_GetCounterH32(GPT_NUM);
void GPT_SetCompareL32(GPT_NUM, UINT32);
void GPT_SetCompareH32(GPT_NUM, UINT32);
UINT32 GPT_GetCompareL32(GPT_NUM);
UINT32 GPT_GetCompareH32(GPT_NUM);

#endif
