/* Copyright Statement:
 *
 * This software/firmware and related documentation ("MediaTek Software") are
 * protected under relevant copyright laws. The information contained herein
 * is confidential and proprietary to MediaTek Inc. and/or its licensors.
 * Without the prior written permission of MediaTek inc. and/or its licensors,
 * any reproduction, modification, use or disclosure of MediaTek Software,
 * and information contained herein, in whole or in part, shall be strictly prohibited.
 */
/* MediaTek Inc. (C) 2010. All rights reserved.
 *
 * BY OPENING THIS FILE, RECEIVER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
 * THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
 * RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO RECEIVER ON
 * AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
 * NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
 * SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
 * SUPPLIED WITH THE MEDIATEK SOFTWARE, AND RECEIVER AGREES TO LOOK ONLY TO SUCH
 * THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. RECEIVER EXPRESSLY ACKNOWLEDGES
 * THAT IT IS RECEIVER'S SOLE RESPONSIBILITY TO OBTAIN FROM ANY THIRD PARTY ALL PROPER LICENSES
 * CONTAINED IN MEDIATEK SOFTWARE. MEDIATEK SHALL ALSO NOT BE RESPONSIBLE FOR ANY MEDIATEK
 * SOFTWARE RELEASES MADE TO RECEIVER'S SPECIFICATION OR TO CONFORM TO A PARTICULAR
 * STANDARD OR OPEN FORUM. RECEIVER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND
 * CUMULATIVE LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
 * AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
 * OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY RECEIVER TO
 * MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE.
 */

/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of MediaTek Inc. (C) 2008
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
*  RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE MEDIATEK SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. MEDIATEK SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE. 
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*****************************************************************************/

/*****************************************************************************
 *
 * Filename:
 * ---------
 *    wdt_hw.h
 *
 * Project:
 * --------
 *   MT3351 FPGA
 *
 * Description:
 * ------------
 *   This file is intends for MT3351 WDT driver.
 *
 * Author:
 * -------
 *  Kelvin Yang (MTK01638)
 *
 ****************************************************************************/
#ifndef _WDT_HW_H
#define _WDT_HW_H

#define MT3351_WDT_BASE                 RGU_BASE                           

#define 	MT3351_WDT_MODE   	        (MT3351_WDT_BASE+0x0000)
#define 	MT3351_WDT_LENGTH 	        (MT3351_WDT_BASE+0x0004)
#define 	MT3351_WDT_RESTART 	        (MT3351_WDT_BASE+0x0008)
#define 	MT3351_WDT_STATUS  	        (MT3351_WDT_BASE+0x000C)
#define 	MT3351_MCU_PERIPH_RESET     (MT3351_WDT_BASE+0x0010)
#define 	MT3351_MM_PERIPH_RESET 	    (MT3351_WDT_BASE+0x0014)
#define		MT3351_WDT_RSTL				(MT3351_WDT_BASE+0x0018)
#define		MT3351_WDT_STRG				(MT3351_WDT_BASE+0x001C)
                                         
/*WDT_MODE*/
#define 	MT3351_WDT_MODE_KEYMASK	    0xff00
#define 	MT3351_WDT_MODE_KEY		    0x2200
#define 	MT3351_WDT_PWR_KEY_DIS      0x0004
#define 	MT3351_WDT_MODE_AUTORST     0x0010
#define 	MT3351_WDT_RESET_IRQ        0x0008
#define 	MT3351_WDT_MODE_ENABLE		0x0001


/*WDT_LENGTH*/
#define 	MT3351_WDT_LENGTH_TOUT		0xffe0
#define 	MT3351_WDT_LENGTH_KEYMASK	0x001f
#define 	MT3351_WDT_LENGTH_KEY		0x0008

/*WDT_RESTART*/
#define 	MT3351_WDT_RESTART_KEY		0x1971

/*WDT_STATUS*/
#define 	MT3351_WDT_STATUS_HWWDT	    0x8000
#define 	MT3351_WDT_STATUS_SWWDT  	0x4000

/*MT3351_MCU_PERIPH_RESET*/
#define 	MT3351_MCU_PERIPH_RESET_KEY_MASK 0xFF000000
#define 	MT3351_MCU_PERIPH_RESET_KEY	0x37000000

typedef enum
{
    MT3351_MCU_PERI_USB	=	0,
    MT3351_MCU_PERI_EMI	=	1,
    MT3351_MCU_PERI_IRQ	=	2,
    MT3351_MCU_PERI_DMA	=	3,
    MT3351_MCU_PERI_RESERVED0	=	4,
    MT3351_MCU_PERI_UART0	=	5,
    MT3351_MCU_PERI_UART1	=	6,
    MT3351_MCU_PERI_UART2	=	7,
    MT3351_MCU_PERI_UART3	=	8,
    MT3351_MCU_PERI_UART4	=	9,
    MT3351_MCU_PERI_GPT	=	10,
    MT3351_MCU_PERI_PWM	=	11,
    MT3351_MCU_PERI_RTC	=	12,
    MT3351_MCU_PERI_I2C	=	13,
    MT3351_MCU_PERI_MSDC0	=	14,
    MT3351_MCU_PERI_MSDC1	=	15,
    MT3351_MCU_PERI_MSDC2	=	16,
    MT3351_MCU_PERI_NFI	=	17,
    MT3351_MCU_PERI_RESERVED1	=	18,
    MT3351_MCU_PERI_SPIFLASH	=	19,
    MT3351_MCU_PERI_AUXADC	=	20,
    MT3351_MCU_PERI_SLEEPCTRL	=	21,
    MT3351_MCU_PERI_KEYPAD	=	22,
    MT3351_MCU_PERI_IRDA	=	23
}MT3351_MCU_PERIPH;

/*MM_PERIPH_RESET*/
#define 	MT3351_MCU_PERIPH_RESET_KEY_MASK	0xFF000000
#define 	MT3351_MM_PERIPH_RESET_KEY		    0x38000000
typedef enum
{
    MT3351_MM_PERI_GBLRST	=	0,
    MT3351_MM_PERI_DSP	=	1,
    MT3351_MM_PERI_GMC	=	2,
    MT3351_MM_PERI_G2D	=	3,
    MT3351_MM_PERI_GCMQ	=	4,
    MT3351_MM_PERI_RESERVED0	=	5,
    MT3351_MM_PERI_JPEG	=	6,
    MT3351_MM_PERI_IMAGEDMA	=	7,
    MT3351_MM_PERI_CAMERAIF	=	8,
    MT3351_MM_PERI_IMAGE_PROCESSOR	=	9,
    MT3351_MM_PERI_PREVIEW_RESIZER	=	10,
    MT3351_MM_PERI_CAPTURE_RESIZER	=	11,
    MT3351_MM_PERI_DROP_RESIZER	=	12,
    MT3351_MM_PERI_AUDIO_SRC_MIX	=	13,
    MT3351_MM_PERI_RESERVED1	=	14,
    MT3351_MM_PERI_VOICE_FRONT_END	=	15,
    MT3351_MM_PERI_SPI	=	16,
    MT3351_MM_PERI_DSP_INTERFACE	=	17,
    MT3351_MM_PERI_BACKLIGHT	=	18,
    MT3351_MM_PERI_RESERVED2	=	19,
    MT3351_MM_PERI_DECOMPRESS	=	20,
    MT3351_MM_PERI_DPI	=	21,
    MT3351_MM_PERI_LCD	=	22,
    MT3351_MM_PERI_RESERVED3	=	23
}MT3351_MM_PERIPH;


/*WDT_RSTL*/
#define 	MT3351_RSTL_MASK		  0x0FFF



/*WDT_STRG*/
#define 	MT3351_WDT_STRG_KEY		  0x1209

#endif   /*_WDT_HW_H*/

